version: '3'
services:

  server:
    image: nginx:alpine
    container_name: server
    volumes:
      - ./:/var/www
      ## copy nginx configuration for our application ##
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      ## run the webserver on port 8080 ##
      - "8080:80"
    networks:
      - app-network

  app:
    ## read php image from our custom docker image ##
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: app
    volumes:
      - ./:/var/www
      ## copy php configuration for our application ##
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www
    networks:
      - app-network

  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
      MYSQL_ROOT_PASSWORD: laravel_root_password
    volumes:
      - dbdata:/var/lib/mysql
      ## copy db configuration for our application ##
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  dbdata: